/*
 * This script downloads federal domains from USA.gov and generates
 * config/domains.js with an array of domains. Running this script
 * will overwrite that file with new domains. This should be Running
 * periodically to keep up with need domains.
 *
 */
var fs = require('fs'),
    path = require('path'),
    async = require('async'),
    _ = require('underscore'),
    request = require('request');

var domains = [
      // Federal non-.gov domains
      {
        url: 'http://govt-urls.usa.gov/tematres/vocab/services.php?output=json&task=fetchDown&arg=17',
        json: true,
      },
      // Federal .gov domains
      {
        url: 'http://govt-urls.usa.gov/tematres/vocab/services.php?output=json&task=fetchDown&arg=11928',
        json: true
      }
    ];

async.map(domains, get, function(err, domains) {
  if (err) return console.error(err);

  // Add .mil domains
  domains.push({ result: { mil: { string: '.mil' } } });

  domains = _(domains).chain().pluck('result').reduce(function(memo, values) {
    return _(memo).extend(values);
  }, {}).values().pluck('string').unique().value().sort();
  var content = '/* This file is automatically generated ' +
        'by ../tools/updateDomains.js */\n\n' +
        'module.exports.domains = ' +
        JSON.stringify(domains, null, 4) + ';\n',
      file = path.join(__dirname, '../config', 'domains.js');
  fs.writeFile(file, content, function(err) {
    if (err) console.error(err);
    else console.log('Successfully wrote to ../config/domains.js');
  });
});

function get(domain, callback) {
  request.get(domain, function(err, res, json) {
    if (err) return callback(err);
    callback(null, json);
  });
}
