source 'https://api.berkshelf.com'

cookbook 'midas', path: 'site-cookbooks/midas'
cookbook 'postgresql', git: 'https://github.com/phlipper/chef-postgresql.git'
cookbook 'nginx'
cookbook 'nodejs'
cookbook 'apt', git: 'git@github.com:opscode-cookbooks/apt.git'
cookbook 'build-essential'

