source 'https://api.berkshelf.com'

cookbook 'midas', path: 'site-cookbooks/midas'
cookbook 'postgresql', git: 'https://github.com/phlipper/chef-postgresql.git'
cookbook 'nginx'
cookbook 'nodejs'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'citadel', git: 'https://github.com/dlapiduz/citadel.git'
